[package]
name = "lunatic-common-api"
version = "0.10.0"
edition = "2021"
description = "Common functionality for building lunatic host function APIs."
homepage = "https://lunatic.solutions"
repository = "https://github.com/lunatic-solutions/lunatic/tree/main/crates/lunatic-common-api"
license = "Apache-2.0/MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime" } # managed by root Cargo.toml
paste = "^1.0"
